const $=s=>document.querySelector(s);
const COLORS=['#2487f3','#e84444','#32ad55','#e6ad19','#9b59d0','#20a5a5'];
const GROUPS={brown:['City Core','#9a633b'],cyan:['Coastal','#48b9d3'],pink:['East','#b35ba7'],orange:['Central','#e58b31'],red:['North','#d9544d'],yellow:['Parklands','#d7b52d'],green:['Premium','#4b9f59'],blue:['Landmarks','#3975b9']};
const SPACES=[
{name:'START',type:'start'},{name:'Victoria Square',type:'property',price:120,rent:14,build:60,group:'brown'},{name:'Chance',type:'chance'},{name:'Central Market',type:'property',price:140,rent:16,build:70,group:'brown'},{name:'Community Chest',type:'chest'},{name:'Hutt St',type:'property',price:160,rent:18,build:80,group:'cyan'},{name:'East End',type:'property',price:180,rent:20,build:90,group:'cyan'},{name:'Jail',type:'jail'},{name:'Burnside',type:'property',price:300,rent:34,build:150,group:'pink'},{name:'Chance',type:'chance'},{name:'Unley',type:'property',price:280,rent:30,build:140,group:'pink'},{name:'Community Chest',type:'chest'},{name:'The Parade',type:'property',price:260,rent:28,build:130,group:'orange'},{name:'Norwood',type:'property',price:240,rent:26,build:120,group:'orange'},{name:'Free Parking',type:'free'},{name:'King William St',type:'property',price:220,rent:24,build:110,group:'red'},{name:'Adelaide Oval',type:'property',price:240,rent:26,build:120,group:'red'},{name:'Chance',type:'chance'},{name:'Rundle Mall',type:'property',price:220,rent:24,build:110,group:'yellow'},{name:'Community Chest',type:'chest'},{name:'North Adelaide',type:'property',price:200,rent:22,build:100,group:'yellow'},{name:'Glenelg',type:'property',price:200,rent:22,build:100,group:'green'},{name:'Brighton',type:'property',price:180,rent:20,build:90,group:'green'},{name:'Port Adelaide',type:'property',price:180,rent:20,build:90,group:'blue'},{name:'Semaphore',type:'property',price:160,rent:18,build:80,group:'blue'}];
const CHANCE=[{text:'Festival bonus：收取 $150。',cash:150},{text:'泊車罰款：支付 $80。',cash:-80},{text:'Go to Jail：立即入獄。',jail:true},{text:'旅遊優惠：前進 3 格。',move:3},{text:'商業回贈：收取 $100。',cash:100},{text:'維修費：每幢屋支付 $25。',perHouse:-25}];
const CHEST=[{text:'生日禮物：收取 $100。',cash:100},{text:'醫療費：支付 $60。',cash:-60},{text:'社區獎勵：收取 $80。',cash:80},{text:'Go to Jail：立即入獄。',jail:true},{text:'交通退款：收取 $50。',cash:50},{text:'慈善捐款：支付 $40。',cash:-40}];
const DICE=['⚀','⚁','⚂','⚃','⚄','⚅'];
let state={version:4,players:[],current:0,rolled:false,lastDice:null,owners:{},houses:{},mortgaged:{},winner:null,log:[],settings:{sound:true,vibration:true,privacy:true,fastAnimation:false}};
let animating=false,pendingTrade=null,auction=null,audioCtx=null;
const setupPanel=$('#setupPanel'),gamePanel=$('#gamePanel'),playerInputs=$('#playerInputs');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function getSettings(){try{return{sound:true,vibration:true,privacy:true,fastAnimation:false,...JSON.parse(localStorage.getItem('adelaideTycoonSettings')||'{}')}}catch{return{sound:true,vibration:true,privacy:true,fastAnimation:false}}}
function saveSettings(){localStorage.setItem('adelaideTycoonSettings',JSON.stringify(state.settings));}
function beep(freq=520,d=.07,type='sine'){if(!state.settings.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function haptic(p=18){if(state.settings.vibration&&navigator.vibrate)navigator.vibrate(p)}
function addPlayerInput(name=''){if(playerInputs.children.length>=6)return;const i=playerInputs.children.length,row=document.createElement('div');row.className='player-row';row.innerHTML=`<div class="pawn-preview" style="--pawn:${COLORS[i]}">♟</div><input maxlength="16" value="${esc(name)}" placeholder="玩家 ${i+1}"><button class="remove-btn">−</button>`;row.querySelector('button').onclick=()=>{if(playerInputs.children.length>2){row.remove();[...playerInputs.children].forEach((r,n)=>r.querySelector('.pawn-preview').style.setProperty('--pawn',COLORS[n]))}};playerInputs.appendChild(row)}
function resetSetup(){playerInputs.innerHTML='';['Alpha','Jason','Cathy','Tony'].forEach(addPlayerInput)}resetSetup();
function freshPlayer(name,i){return{name,cash:1500,pos:0,color:COLORS[i],assets:[],inJail:false,jailTurns:0,bankrupt:false}}
function startGame(){const names=[...playerInputs.querySelectorAll('input')].map((x,i)=>x.value.trim()||`玩家 ${i+1}`);if(names.length<2)return;state={version:4,players:names.map(freshPlayer),current:0,rolled:false,lastDice:null,owners:{},houses:{},mortgaged:{},winner:null,log:['遊戲開始。'],settings:getSettings()};setupPanel.classList.add('hidden');gamePanel.classList.remove('hidden');msg(`${names[0]} 先行，按「擲骰」。`);render();save()}
function grid(i){const c=[];for(let x=1;x<=6;x++)c.push([6,x]);for(let y=5;y>=1;y--)c.push([y,6]);for(let x=5;x>=1;x--)c.push([1,x]);for(let y=2;y<=5;y++)c.push([y,1]);return c[i]}
function groupIds(g){return SPACES.map((s,i)=>s.group===g?i:null).filter(i=>i!==null)}
function ownsGroup(pi,g){const a=groupIds(g);return a.length&&a.every(i=>state.owners[i]===pi&&!state.mortgaged[i])}
function rent(i){const s=SPACES[i];if(state.mortgaged[i])return 0;const h=state.houses[i]||0;return s.rent*(h+1)*(h===0&&ownsGroup(state.owners[i],s.group)?2:1)}
function canBuild(pi,i){const s=SPACES[i];if(!s?.group||state.owners[i]!==pi||state.mortgaged[i]||!ownsGroup(pi,s.group)||(state.houses[i]||0)>=4)return false;const a=groupIds(s.group).map(x=>state.houses[x]||0);return(state.houses[i]||0)===Math.min(...a)}
function canSell(pi,i){const s=SPACES[i];if(!s?.group||state.owners[i]!==pi||(state.houses[i]||0)<=0)return false;const a=groupIds(s.group).map(x=>state.houses[x]||0);return(state.houses[i]||0)===Math.max(...a)}
function renderBoard(){const b=$('#board');b.innerHTML='<div class="space center"><div><div class="center-title">ADELAIDE<br>TYCOON</div><div class="deck-row"><span class="deck chance-deck">?</span><span class="deck chest-deck">✦</span></div><div class="center-sub">買地 · 建屋 · 交易 · 拍賣</div></div></div>';SPACES.forEach((s,i)=>{const [r,c]=grid(i),d=document.createElement('div');d.className=`space type-${s.type}${state.mortgaged[i]?' mortgaged':''}${state.players[state.current]?.pos===i?' active-space':''}`;d.dataset.index=i;d.style.gridRow=r;d.style.gridColumn=c;let icon=s.type==='chance'?'?':s.type==='chest'?'✦':s.type==='jail'?'🚔':s.type==='free'?'🚗':s.type==='start'?'GO':'';d.innerHTML=`${s.group?`<div class="group-band" style="background:${GROUPS[s.group][1]}"></div>`:''}<div class="label">${s.name}</div>${icon?`<div class="space-icon">${icon}</div>`:''}${s.price?`<div class="price">$${s.price}</div>`:''}${state.houses[i]?`<div class="houses">${'▰'.repeat(state.houses[i])}</div>`:''}${state.mortgaged[i]?'<div class="mortgage-tag">抵押</div>':''}<div class="token-row"></div>`;state.players.forEach((p,pi)=>{if(!p.bankrupt&&p.pos===i){const t=document.createElement('span');t.className='pawn-token'+(pi===state.current?' current-token':'');t.style.setProperty('--pawn',p.color);t.textContent='♟';d.querySelector('.token-row').appendChild(t)}});b.appendChild(d)})}
function renderPlayers(){const s=$('#playersStrip');s.innerHTML='';state.players.forEach((p,i)=>{const net=p.cash+p.assets.reduce((n,x)=>n+Math.round(SPACES[x].price/2),0),d=document.createElement('div');d.className='player-card'+(i===state.current&&!p.bankrupt?' active':'')+(p.bankrupt?' bankrupt':'');d.innerHTML=`<div class="player-top"><span class="mini-pawn" style="--pawn:${p.color}">♟</span><div><div class="name">${esc(p.name)}${p.inJail?' 🚔':''}</div><div class="cash">${p.bankrupt?'已破產':`$${p.cash}`}</div></div></div><div class="net">資產值 ~$${net}</div>`;s.appendChild(d)})}
function renderInfo(){const p=state.players[state.current],s=SPACES[p.pos];$('#turnName').textContent=p.name;$('#turnPos').textContent=`第 ${p.pos} 格`;$('#die1').textContent=state.lastDice?DICE[state.lastDice.d1-1]:'–';$('#die2').textContent=state.lastDice?DICE[state.lastDice.d2-1]:'–';$('#jailStatus').textContent=p.inJail?`🚔 ${p.jailTurns}/3`:'正常';$('#spaceType').textContent=s.group?GROUPS[s.group][0]:'目前位置';$('#spaceName').textContent=s.name;$('#spaceMeta').textContent=s.type==='property'?`售價 $${s.price} · 租金 $${rent(p.pos)} · 建屋 $${s.build}${state.owners[p.pos]!=null?` · ${state.players[state.owners[p.pos]].name} 擁有`:''}${state.mortgaged[p.pos]?' · 已抵押':''}`:s.type==='start'?'經過 START 收 $200':s.type==='jail'?'探監／被送入獄時停留':s.type==='free'?'免費泊車':'抽取事件卡';for(const id of ['buyBtn','auctionBtn','buildBtn'])$('#'+id).classList.add('hidden');$('#endTurnBtn').classList.toggle('hidden',!state.rolled);if(state.rolled&&s.type==='property'&&state.owners[p.pos]==null){if(p.cash>=s.price)$('#buyBtn').classList.remove('hidden');$('#auctionBtn').classList.remove('hidden')}if(state.rolled&&canBuild(state.current,p.pos)&&p.cash>=s.build){$('#buildBtn').classList.remove('hidden');$('#buildBtn').textContent=`建屋 $${s.build}`}$('#rollBtn').disabled=state.rolled||animating||!!state.winner}
function renderLog(){$('#gameLog').innerHTML=state.log.map(x=>`<div>${esc(x)}</div>`).join('')||'<div>未有紀錄。</div>'}
function render(){renderPlayers();renderBoard();renderInfo();renderLog()}
function msg(t){$('#message').textContent=t}function log(t){state.log.unshift(t);state.log=state.log.slice(0,24)}
async function animateDice(){const a=$('#die1'),b=$('#die2');a.classList.add('rolling');b.classList.add('rolling');for(let i=0;i<8;i++){a.textContent=DICE[Math.floor(Math.random()*6)];b.textContent=DICE[Math.floor(Math.random()*6)];await sleep(55)}a.classList.remove('rolling');b.classList.remove('rolling')}
async function move(p,n){animating=true;for(let x=0;x<n;x++){const old=p.pos;p.pos=(p.pos+1)%SPACES.length;if(p.pos<old){p.cash+=200;log(`${p.name} 經過 START，收取 $200。`);beep(820,.05,'triangle')}renderBoard();renderPlayers();document.querySelector(`.space[data-index="${p.pos}"] .current-token`)?.classList.add('moving');await sleep(state.settings.fastAnimation?65:135)}animating=false;document.querySelector(`.space[data-index="${p.pos}"]`)?.classList.add('just-landed');haptic(15)}
async function rollDice(){if(state.rolled||animating||state.winner)return;const p=state.players[state.current];await animateDice();const d1=1+Math.floor(Math.random()*6),d2=1+Math.floor(Math.random()*6),sum=d1+d2;state.lastDice={d1,d2,sum};state.rolled=true;beep(430,.05);setTimeout(()=>beep(560,.07),55);haptic(25);if(p.inJail){p.jailTurns++;if(d1===d2){p.inJail=false;p.jailTurns=0;msg(`${p.name} 擲到雙骰，成功出獄！`);await move(p,sum);await resolve(p.pos)}else if(p.jailTurns>=3){p.cash-=50;p.inJail=false;p.jailTurns=0;msg(`${p.name} 支付 $50 出獄。`);await move(p,sum);await resolve(p.pos)}else msg(`${p.name} 未擲到雙骰，仍然留喺監獄。`)}else{await move(p,sum);await resolve(p.pos)}checkCash(p);checkWinner();render();save()}
async function resolve(i){const p=state.players[state.current],s=SPACES[i];if(s.type==='property'&&state.owners[i]!=null&&state.owners[i]!==state.current){const o=state.players[state.owners[i]],r=rent(i);if(r){const paid=Math.min(r,Math.max(0,p.cash));p.cash-=r;o.cash+=paid;msg(`${p.name} 要向 ${o.name} 支付租金 $${r}。`);log(`${p.name} → ${s.name}，租金 $${r}。`)}else msg(`${s.name} 已抵押，毋須交租。`)}else if(s.type==='property'){msg(`${p.name} 去到 ${s.name}。${state.owners[i]==null?`可用 $${s.price} 購買或拍賣。`:'你已擁有呢個地產。'}`)}else if(s.type==='chance'||s.type==='chest')await drawCard(s.type);else{msg(`${p.name} 去到 ${s.name}。`);log(`${p.name} → ${s.name}。`)}}
async function drawCard(type){const p=state.players[state.current],deck=type==='chance'?CHANCE:CHEST,c=deck[Math.floor(Math.random()*deck.length)];if(c.cash)p.cash+=c.cash;if(c.perHouse)p.cash+=c.perHouse*p.assets.reduce((a,i)=>a+(state.houses[i]||0),0);if(c.jail){p.pos=7;p.inJail=true;p.jailTurns=0}msg(`${type==='chance'?'Chance':'Community Chest'}：${c.text}`);log(`${p.name} 抽卡：${c.text}`);const dlg=$('#cardModal');dlg.querySelector('.event-card').classList.toggle('chest',type==='chest');$('#eventCardIcon').textContent=type==='chest'?'✦':'?';$('#eventCardType').textContent=type==='chest'?'COMMUNITY CHEST':'CHANCE';$('#eventCardText').textContent=c.text;beep(type==='chest'?620:760,.12,'triangle');haptic([20,35,20]);dlg.showModal();if(c.move&&!c.jail){await move(p,c.move);await resolve(p.pos)}}
function buyCurrent(){const p=state.players[state.current],i=p.pos,s=SPACES[i];if(s.type!=='property'||state.owners[i]!=null||p.cash<s.price)return;p.cash-=s.price;state.owners[i]=state.current;p.assets.push(i);msg(`${p.name} 已用 $${s.price} 購買 ${s.name}。`);log(`${p.name} 購買 ${s.name}。`);beep(660,.09,'triangle');haptic([15,20,15]);render();save()}
function buildCurrent(){const p=state.players[state.current],i=p.pos,s=SPACES[i];if(!canBuild(state.current,i)||p.cash<s.build)return;p.cash-=s.build;state.houses[i]=(state.houses[i]||0)+1;msg(`${p.name} 喺 ${s.name} 建咗第 ${state.houses[i]} 幢屋。`);log(`${p.name} 喺 ${s.name} 建屋。`);beep(720,.08,'triangle');haptic(20);render();save()}
function checkCash(p){if(p.cash<=0&&p.assets.length)msg(`${p.name} 現金不足，可抵押、賣屋或交易自救。`)}
function bankrupt(i){const p=state.players[i];p.bankrupt=true;p.assets.forEach(x=>{delete state.owners[x];delete state.houses[x];delete state.mortgaged[x]});p.assets=[];log(`${p.name} 已破產。`)}
function checkWinner(){const a=state.players.filter(p=>!p.bankrupt);if(a.length===1&&state.players.length>1){state.winner=a[0].name;$('#winnerName').textContent=a[0].name;$('#winnerModal').showModal();log(`${a[0].name} 勝出！`)}}
function endTurn(){if(!state.rolled||state.winner)return;const p=state.players[state.current];if(p.cash<=0)bankrupt(state.current);checkWinner();if(state.winner){render();save();return}do{state.current=(state.current+1)%state.players.length}while(state.players[state.current].bankrupt);state.rolled=false;state.lastDice=null;msg(`下一位：${state.players[state.current].name}。`);render();save();if(state.settings.privacy){$('#passPlayerName').textContent=state.players[state.current].name;$('#passModal').showModal()}}
function assetValue(i){return Math.round(SPACES[i].price/2)}
function showAssets(){const p=state.players[state.current];$('#modalTitle').textContent=`${p.name} 的資產`;$('#modalBody').innerHTML=p.assets.length?`<div class="asset-list">${p.assets.map(i=>{const s=SPACES[i],h=state.houses[i]||0,m=!!state.mortgaged[i];return`<div class="asset-card"><div class="asset-band" style="background:${GROUPS[s.group][1]}"></div><div class="asset-main"><div><strong>${s.name}</strong><small>${GROUPS[s.group][0]} · ${h} 幢屋 · 租 $${rent(i)}</small></div><span class="${m?'status-mortgaged':'status-owned'}">${m?'已抵押':'持有'}</span></div><div class="asset-actions">${canSell(state.current,i)?`<button class="mini-btn sell-house" data-i="${i}">賣屋 +$${Math.round(s.build/2)}</button>`:''}${h===0?`<button class="mini-btn mortgage" data-i="${i}">${m?`解除抵押 -$${Math.ceil(assetValue(i)*1.1)}`:`抵押 +$${assetValue(i)}`}</button>`:''}</div></div>`}).join('')}</div>`:'<p>暫時未有地產。</p>';$('#modal').showModal();document.querySelectorAll('.mortgage').forEach(b=>b.onclick=()=>toggleMortgage(+b.dataset.i));document.querySelectorAll('.sell-house').forEach(b=>b.onclick=()=>sellHouse(+b.dataset.i))}
function toggleMortgage(i){const p=state.players[state.current],s=SPACES[i],v=assetValue(i);if(state.houses[i])return;if(state.mortgaged[i]){const c=Math.ceil(v*1.1);if(p.cash<c)return alert('現金不足。');p.cash-=c;delete state.mortgaged[i]}else{p.cash+=v;state.mortgaged[i]=true}log(`${p.name} ${state.mortgaged[i]?'抵押':'解除抵押'} ${s.name}。`);save();render();showAssets()}
function sellHouse(i){const p=state.players[state.current],s=SPACES[i];if(!canSell(state.current,i))return;state.houses[i]--;p.cash+=Math.round(s.build/2);log(`${p.name} 喺 ${s.name} 賣出一幢屋。`);save();render();showAssets()}
function showPlayers(){$('#modalTitle').textContent='玩家資料';$('#modalBody').innerHTML=`<div class="asset-list">${state.players.map(p=>`<div class="asset-item"><span><b style="color:${p.color}">♟</b> ${esc(p.name)}${p.inJail?' 🚔':''}</span><strong>${p.bankrupt?'破產':`$${p.cash}`}</strong></div>`).join('')}</div>`;$('#modal').showModal()}
function showTrade(){const me=state.players[state.current],others=state.players.map((p,i)=>({p,i})).filter(x=>x.i!==state.current&&!x.p.bankrupt);if(!others.length)return;$('#modalTitle').textContent='提出交易';$('#modalBody').innerHTML=`<div class="trade-grid"><label>交易對象<select id="tradePlayer">${others.map(x=>`<option value="${x.i}">${esc(x.p.name)}</option>`).join('')}</select></label><label>你支付現金<input id="tradeCashGive" type="number" min="0" value="0"></label><label>要求對方支付<input id="tradeCashGet" type="number" min="0" value="0"></label><label>你交出地產<select id="tradeGiveAsset"><option value="">不交地產</option>${me.assets.filter(i=>!state.houses[i]).map(i=>`<option value="${i}">${SPACES[i].name}</option>`).join('')}</select></label><label>要求取得地產<select id="tradeGetAsset"></select></label><button id="previewTrade" class="primary-btn">交俾對方確認</button></div>`;const ps=$('#tradePlayer'),ga=$('#tradeGetAsset'),refresh=()=>{ga.innerHTML='<option value="">不取地產</option>'+state.players[+ps.value].assets.filter(i=>!state.houses[i]).map(i=>`<option value="${i}">${SPACES[i].name}</option>`).join('')};refresh();ps.onchange=refresh;$('#previewTrade').onclick=()=>{const oi=+ps.value,g=+$('#tradeCashGive').value||0,r=+$('#tradeCashGet').value||0;if(g>me.cash||r>state.players[oi].cash)return alert('現金不足。');pendingTrade={from:state.current,to:oi,give:g,get:r,ga:$('#tradeGiveAsset').value,ra:ga.value};$('#modal').close();$('#confirmTitle').textContent=`請將電話交俾 ${state.players[oi].name}`;$('#confirmBody').innerHTML=`<div class="trade-summary">${me.name} 支付 $${g}${pendingTrade.ga?` + ${SPACES[+pendingTrade.ga].name}`:''}<br>換取 $${r}${pendingTrade.ra?` + ${SPACES[+pendingTrade.ra].name}`:''}</div>`;$('#confirmModal').showModal()};$('#modal').showModal()}
function transfer(i,a,b){i=+i;const x=state.players[a],y=state.players[b],k=x.assets.indexOf(i);if(k>=0){x.assets.splice(k,1);y.assets.push(i);state.owners[i]=b}}
function acceptTrade(){const t=pendingTrade;if(!t)return;const a=state.players[t.from],b=state.players[t.to];if(t.give>a.cash||t.get>b.cash)return alert('現金不足。');a.cash=a.cash-t.give+t.get;b.cash=b.cash-t.get+t.give;if(t.ga)transfer(t.ga,t.from,t.to);if(t.ra)transfer(t.ra,t.to,t.from);log(`${a.name} 同 ${b.name} 完成交易。`);pendingTrade=null;$('#confirmModal').close();render();save()}
function startAuction(){const i=state.players[state.current].pos;if(SPACES[i].type!=='property'||state.owners[i]!=null)return;auction={space:i,bid:0,bidder:null};renderAuction();$('#modal').showModal()}
function renderAuction(){$('#modalTitle').textContent=`拍賣：${SPACES[auction.space].name}`;const alive=state.players.map((p,i)=>({p,i})).filter(x=>!x.p.bankrupt);$('#modalBody').innerHTML=`<div class="auction-box"><div class="auction-price"><span>最高出價</span><strong>$${auction.bid}</strong><small>${auction.bidder==null?'未有人出價':state.players[auction.bidder].name}</small></div><label>出價玩家<select id="auctionPlayer">${alive.map(x=>`<option value="${x.i}">${esc(x.p.name)}（$${x.p.cash}）</option>`).join('')}</select></label><div class="bid-row"><button class="bid-btn" data-add="10">+$10</button><button class="bid-btn" data-add="50">+$50</button><button class="bid-btn" data-add="100">+$100</button></div><button id="finishAuction" class="primary-btn" ${auction.bidder==null?'disabled':''}>成交</button></div>`;document.querySelectorAll('.bid-btn').forEach(b=>b.onclick=()=>{const pi=+$('#auctionPlayer').value,n=auction.bid+(+b.dataset.add);if(n>state.players[pi].cash)return alert('現金不足。');auction.bid=n;auction.bidder=pi;renderAuction()});$('#finishAuction').onclick=()=>{if(auction.bidder==null)return;const p=state.players[auction.bidder];p.cash-=auction.bid;p.assets.push(auction.space);state.owners[auction.space]=auction.bidder;log(`${p.name} 以 $${auction.bid} 拍得 ${SPACES[auction.space].name}。`);auction=null;$('#modal').close();render();save()}}
function openSettings(){const s=state.settings;$('#soundToggle').checked=s.sound;$('#vibrationToggle').checked=s.vibration;$('#privacyToggle').checked=s.privacy;$('#fastAnimationToggle').checked=s.fastAnimation;$('#settingsModal').showModal()}
function save(){try{localStorage.setItem('adelaideTycoonState',JSON.stringify(state))}catch{}}
function migrate(s){s.version=4;s.settings={...getSettings(),...(s.settings||{})};s.owners=s.owners||{};s.houses=s.houses||{};s.mortgaged=s.mortgaged||{};s.log=s.log||[];s.players=(s.players||[]).map(p=>({...p,assets:p.assets||[],inJail:!!p.inJail,jailTurns:p.jailTurns||0,bankrupt:!!p.bankrupt}));return s}
function load(){try{const s=JSON.parse(localStorage.getItem('adelaideTycoonState'));if(s?.players?.length){state=migrate(s);setupPanel.classList.add('hidden');gamePanel.classList.remove('hidden');render();msg(`已載入上次遊戲。現在到 ${state.players[state.current].name}。`)}}catch{}}
function newGame(){localStorage.removeItem('adelaideTycoonState');location.reload()}
$('#addPlayerBtn').onclick=()=>addPlayerInput('');$('#startGameBtn').onclick=startGame;$('#rollBtn').onclick=rollDice;$('#buyBtn').onclick=buyCurrent;$('#auctionBtn').onclick=startAuction;$('#buildBtn').onclick=buildCurrent;$('#endTurnBtn').onclick=endTurn;$('#assetsBtn').onclick=showAssets;$('#tradeBtn').onclick=showTrade;$('#playersBtn').onclick=showPlayers;$('#closeModalBtn').onclick=()=>$('#modal').close();$('#newGameBtn').onclick=newGame;$('#settingsBtn').onclick=openSettings;$('#closeSettingsBtn').onclick=()=>$('#settingsModal').close();$('#eventCardContinue').onclick=()=>$('#cardModal').close();$('#passContinueBtn').onclick=()=>{$('#passModal').close();beep(520,.05)};$('#rejectTradeBtn').onclick=()=>{pendingTrade=null;$('#confirmModal').close();msg('交易被拒絕。')};$('#acceptTradeBtn').onclick=acceptTrade;$('#closeWinnerBtn').onclick=()=>$('#winnerModal').close();$('#restartWinnerBtn').onclick=newGame;
for(const [id,key] of [['soundToggle','sound'],['vibrationToggle','vibration'],['privacyToggle','privacy'],['fastAnimationToggle','fastAnimation']])$('#'+id).onchange=e=>{state.settings[key]=e.target.checked;saveSettings();save();if(key==='sound'&&e.target.checked)beep(620,.06)};
load();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
