(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const N=42; const tiles=Array.from({length:N},()=>Array.from({length:N},()=>({type:'grass',level:0,age:0}))); 
let tool='select', money=120000,pop=0,happiness=78,paused=false,speed=1,time=8*60, last=performance.now(),acc=0;
let cam={x:0,y:0,zoom:1},drag=false,lastP=null,moved=false,hover=null;
const COST={road:120,res:40,com:50,ind:50,bulldoze:20};
const colors={grass:'#7fa76d',grass2:'#749b63',road:'#42484d',roadEdge:'#70767b',res:'#67b878',com:'#59a8df',ind:'#d7a64d'};
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function iso(x,y,z=0){const s=26*cam.zoom;return {x:innerWidth/2+cam.x+(x-y)*s,y:145+cam.y+(x+y)*s*.5-z*s}}
function screenToGrid(px,py){const s=26*cam.zoom;const X=(px-innerWidth/2-cam.x)/s;const Y=(py-145-cam.y)/(.5*s);return {x:Math.floor((Y+X)/2),y:Math.floor((Y-X)/2)}}
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
function tileDiamond(x,y,fill){let a=iso(x,y),b=iso(x+1,y),c=iso(x+1,y+1),d=iso(x,y+1);poly([a,b,c,d],fill,'rgba(20,40,25,.12)')}
function building(x,y,t,l){const h=(10+l*7)*cam.zoom; const inset=.13; let a=iso(x+inset,y+inset),b=iso(x+1-inset,y+inset),c=iso(x+1-inset,y+1-inset),d=iso(x+inset,y+1-inset);let at={x:a.x,y:a.y-h},bt={x:b.x,y:b.y-h},ct={x:c.x,y:c.y-h},dt={x:d.x,y:d.y-h};let base=t==='res'?'#5c9670':t==='com'?'#578bad':'#9d8554';let top=t==='res'?'#d7e7d2':t==='com'?'#c9dfe9':'#e2c993';poly([d,c,ct,dt],shade(base,-18));poly([b,c,ct,bt],shade(base,-8));poly([at,bt,ct,dt],top,'rgba(0,0,0,.18)');if(l>=2){ctx.fillStyle='rgba(235,248,255,.78)';for(let k=0;k<l+1;k++){let p=iso(x+.3,y+.16);ctx.fillRect(p.x+2*k*cam.zoom,p.y-h+7*cam.zoom,3*cam.zoom,5*cam.zoom)}}}
function shade(hex,amt){let n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,((n>>8)&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return `rgb(${r},${g},${b})`}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);let grd=ctx.createLinearGradient(0,0,0,innerHeight);grd.addColorStop(0,'#9bc6de');grd.addColorStop(.34,'#dce7dc');grd.addColorStop(.35,'#759967');grd.addColorStop(1,'#658b58');ctx.fillStyle=grd;ctx.fillRect(0,0,innerWidth,innerHeight);
ctx.fillStyle='rgba(58,80,65,.24)';ctx.beginPath();ctx.moveTo(0,innerHeight*.35);for(let x=0;x<=innerWidth;x+=80)ctx.lineTo(x,innerHeight*.31+Math.sin(x*.012)*22);ctx.lineTo(innerWidth,innerHeight*.48);ctx.lineTo(0,innerHeight*.48);ctx.fill();
for(let sum=0;sum<N*2-1;sum++)for(let x=0;x<N;x++){let y=sum-x;if(y<0||y>=N)continue;let t=tiles[x][y];let f=t.type==='road'?colors.road:(t.type==='res'?shade(colors.grass,3):t.type==='com'?shade(colors.grass,-2):t.type==='ind'?shade(colors.grass,-5):((x+y)%2?colors.grass:colors.grass2));tileDiamond(x,y,f);if(t.type==='road')drawRoad(x,y);if(['res','com','ind'].includes(t.type)&&t.level>0)building(x,y,t.type,t.level)}
if(hover&&inGrid(hover.x,hover.y)){let a=iso(hover.x,hover.y),b=iso(hover.x+1,hover.y),c=iso(hover.x+1,hover.y+1),d=iso(hover.x,hover.y+1);ctx.save();ctx.globalAlpha=.4;poly([a,b,c,d],tool==='bulldoze'?'#ff6e6e':tool==='road'?'#d2d7db':tool==='res'?colors.res:tool==='com'?colors.com:tool==='ind'?colors.ind:'#fff');ctx.restore()}
requestAnimationFrame(draw)}
function drawRoad(x,y){let p=iso(x+.5,y+.5);let s=26*cam.zoom;ctx.strokeStyle='rgba(255,255,255,.27)';ctx.lineWidth=Math.max(1,cam.zoom);ctx.setLineDash([5*cam.zoom,5*cam.zoom]);ctx.beginPath();ctx.moveTo(p.x-s*.28,p.y+s*.14);ctx.lineTo(p.x+s*.28,p.y-s*.14);ctx.stroke();ctx.setLineDash([])}
function inGrid(x,y){return x>=0&&y>=0&&x<N&&y<N}
function hasRoad(x,y){return [[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>inGrid(x+dx,y+dy)&&tiles[x+dx][y+dy].type==='road')}
function buildAt(g){if(!inGrid(g.x,g.y)||tool==='select')return;let t=tiles[g.x][g.y];if(tool==='bulldoze'){if(t.type!=='grass'&&money>=COST.bulldoze){money-=COST.bulldoze;tiles[g.x][g.y]={type:'grass',level:0,age:0}}}else if(money>=COST[tool]&&t.type!==tool){money-=COST[tool];tiles[g.x][g.y]={type:tool,level:0,age:0}}updateUI()}
function simulate(){time+=7*speed;if(time>=1440)time-=1440;let counts={road:0,res:0,com:0,ind:0};let residents=0,jobs=0;for(let x=0;x<N;x++)for(let y=0;y<N;y++){let t=tiles[x][y];if(counts[t.type]!=null)counts[t.type]++;if(['res','com','ind'].includes(t.type)){t.age++;if(hasRoad(x,y)&&t.level===0&&t.age>3&&Math.random()<.18)t.level=1;if(hasRoad(x,y)&&t.level>0&&t.level<4&&t.age>8&&Math.random()<.025)t.level++;if(t.type==='res')residents+=t.level*18;if(t.type==='com')jobs+=t.level*14;if(t.type==='ind')jobs+=t.level*20}}
pop=residents;let employment=Math.min(1,jobs/Math.max(1,residents*.55));happiness=Math.round(Math.max(42,Math.min(96,72+employment*16-counts.ind*.04)));let income=Math.round(residents*3.1+counts.com*16+counts.ind*18);let expense=Math.round(counts.road*1.1+counts.res*.6+counts.com*.8+counts.ind*.9);money+=Math.max(-5000,(income-expense)/12);updateUI(counts,income,expense)}
function updateUI(c=null,income=null,expense=null){if(!c){c={road:0,res:0,com:0,ind:0};for(let x=0;x<N;x++)for(let y=0;y<N;y++)if(c[tiles[x][y].type]!=null)c[tiles[x][y].type]++}let fmt=n=>Math.round(n).toLocaleString('en-AU');money=Math.max(-999999,money);document.getElementById('money').textContent='$'+fmt(money);document.getElementById('population').textContent=fmt(pop);document.getElementById('happiness').textContent=happiness+'%';document.getElementById('clock').textContent=String(Math.floor(time/60)).padStart(2,'0')+':'+String(Math.floor(time%60)).padStart(2,'0');['res','com','ind','road'].forEach(k=>document.getElementById(k+'Count').textContent=c[k]);let dr=Math.max(10,Math.min(95,72-c.res*1.4+c.com*.6)),dc=Math.max(8,Math.min(95,40+c.res*.7-c.com*1.6)),di=Math.max(8,Math.min(95,34+c.res*.55-c.ind*1.4));document.getElementById('demandR').style.width=dr+'%';document.getElementById('demandC').style.width=dc+'%';document.getElementById('demandI').style.width=di+'%';if(income!=null){document.getElementById('income').textContent='$'+fmt(income);document.getElementById('expense').textContent='$'+fmt(expense)}}
function loop(now){let dt=now-last;last=now;if(!paused){acc+=dt*speed;if(acc>1100){simulate();acc=0}}requestAnimationFrame(loop)}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag=true;lastP={x:e.clientX,y:e.clientY};moved=false});canvas.addEventListener('pointermove',e=>{hover=screenToGrid(e.clientX,e.clientY);if(drag&&lastP){let dx=e.clientX-lastP.x,dy=e.clientY-lastP.y;if(Math.hypot(dx,dy)>3)moved=true;if(tool==='select'||e.buttons===2){cam.x+=dx;cam.y+=dy;lastP={x:e.clientX,y:e.clientY}}}});canvas.addEventListener('pointerup',e=>{if(!moved&&tool!=='select')buildAt(screenToGrid(e.clientX,e.clientY));drag=false;lastP=null});canvas.addEventListener('wheel',e=>{e.preventDefault();cam.zoom=Math.max(.45,Math.min(2.4,cam.zoom*(e.deltaY<0?1.1:.9)))},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.querySelectorAll('.toolbar button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.toolbar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool;canvas.style.cursor=tool==='select'?'grab':'crosshair'});
document.getElementById('pauseBtn').onclick=()=>{paused=!paused;document.getElementById('pauseBtn').textContent=paused?'▶':'⏸'};document.getElementById('speedBtn').onclick=()=>{speed=speed===1?2:speed===2?4:1;document.getElementById('speedBtn').textContent=speed+'×'};
document.getElementById('saveBtn').onclick=()=>{localStorage.setItem('cityforge-save',JSON.stringify({tiles,money,pop,happiness,time,cam}));toast('城市已儲存')};document.getElementById('loadBtn').onclick=()=>{let s=localStorage.getItem('cityforge-save');if(!s)return toast('未有存檔');let d=JSON.parse(s);for(let x=0;x<N;x++)for(let y=0;y<N;y++)tiles[x][y]=d.tiles[x][y];money=d.money;pop=d.pop;happiness=d.happiness;time=d.time;cam=d.cam||cam;updateUI();toast('存檔已讀取')};
function toast(s){let h=document.getElementById('hint');h.textContent=s;h.style.opacity='1';clearTimeout(toast.t);toast.t=setTimeout(()=>{h.textContent='拖動畫面移動 • 滾輪縮放 • 選工具後點擊格子建造'},1800)}
for(let i=7;i<35;i++){tiles[i][20]={type:'road',level:0,age:0};if(i>11&&i<31)tiles[20][i]={type:'road',level:0,age:0}}cam.y=-180;updateUI();draw();requestAnimationFrame(loop);
})();
