import {THREE,scene,terrainHeight,WATER_LEVEL} from './engine.js';
export const state={money:1250000,population:0,jobs:0,hour:8,speed:1,paused:false};
export const roads=[],roadCurves=[],roadSamples=[],zones=[],buildings=[],cars=[];const zoneSet=new Map();
const roadMat=new THREE.MeshStandardMaterial({color:0x33383c,roughness:.92}),previewMat=new THREE.MeshBasicMaterial({color:0x55c7ff,transparent:true,opacity:.55,depthWrite:false});
export function ribbon(curve,width=12,mat=roadMat,lift=.8){const segs=Math.max(12,Math.ceil(curve.getLength()/18)),pts=curve.getPoints(segs),v=[],idx=[];for(let i=0;i<pts.length;i++){const p=pts[i],p0=pts[Math.max(0,i-1)],p1=pts[Math.min(pts.length-1,i+1)],t=p1.clone().sub(p0).setY(0).normalize(),s=new THREE.Vector3(-t.z,0,t.x).multiplyScalar(width/2),y=terrainHeight(p.x,p.z)+lift,l=p.clone().add(s),r=p.clone().sub(s);l.y=r.y=y;v.push(l.x,l.y,l.z,r.x,r.y,r.z);if(i<pts.length-1){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,b,c,b,d,c)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const mesh=new THREE.Mesh(g,mat);mesh.castShadow=mesh.receiveShadow=true;return mesh}
export function previewRoad(points){const c=new THREE.CatmullRomCurve3(points,false,'centripetal',.45);return ribbon(c,12,previewMat,1.8)}
export function makeRoad(points){const c=new THREE.CatmullRomCurve3(points.map(p=>p.clone()),false,'centripetal',.45),len=c.getLength(),cost=Math.round(len*42);if(state.money<cost)return false;state.money-=cost;const mesh=ribbon(c);scene.add(mesh);roads.push(mesh);roadCurves.push(c);roadSamples.push(...c.getPoints(Math.max(8,Math.ceil(len/30))));const stripePts=c.getPoints(Math.max(16,Math.ceil(len/22))).map(p=>new THREE.Vector3(p.x,terrainHeight(p.x,p.z)+1.55,p.z)),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(stripePts),new THREE.LineDashedMaterial({color:0xe8d87b,dashSize:8,gapSize:8,transparent:true,opacity:.85}));line.computeLineDistances();scene.add(line);return {len,cost}}
makeRoad([new THREE.Vector3(-1150,0,-280),new THREE.Vector3(0,0,-120),new THREE.Vector3(1180,0,80)]);makeRoad([new THREE.Vector3(-340,0,-1050),new THREE.Vector3(-160,0,0),new THREE.Vector3(-40,0,1020)]);
const mats={res:[0xd7c9b5,0xc1d3d8,0xe3d7c8,0xb9c9b6],com:[0x8fa8b4,0xa7b5c4,0xc2b8a8],ind:[0x8e8c83,0x9d957f,0x797d78]};for(const k in mats)mats[k]=mats[k].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:k==='com'?.52:.8,metalness:k==='com'?.08:0}));
function nearRoad(x,z,max=55){let best=Infinity;for(const p of roadSamples)best=Math.min(best,(p.x-x)**2+(p.z-z)**2);return Math.sqrt(best)<=max}
const key=(x,z)=>`${Math.round(x/32)},${Math.round(z/32)}`;
export function paintZone(type,x,z){const gx=Math.round(x/32)*32,gz=Math.round(z/32)*32,k=key(gx,gz);if(zoneSet.has(k))return;const y=terrainHeight(gx,gz)+1.2;if(y<WATER_LEVEL+2)return;const color={res:0x4ec66b,com:0x4f8fe8,ind:0xe0b34f}[type],g=new THREE.PlaneGeometry(29,29);g.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.38,depthWrite:false}));mesh.position.set(gx,y,gz);scene.add(mesh);const zt={type,x:gx,z:gz,mesh,built:false};zones.push(zt);zoneSet.set(k,zt)}
function grow(zt){if(!nearRoad(zt.x,zt.z))return false;let w=20,d=20,h=22;if(zt.type==='res'){h=18+Math.random()*55;w=d=18+Math.random()*10}if(zt.type==='com'){h=28+Math.random()*92;w=d=22+Math.random()*14}if(zt.type==='ind'){h=13+Math.random()*18;w=26+Math.random()*14;d=28+Math.random()*18}const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mats[zt.type][(Math.random()*mats[zt.type].length)|0]);mesh.position.set(zt.x,terrainHeight(zt.x,zt.z)+h/2+.8,zt.z);mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);zt.mesh.visible=false;zt.built=true;const b={type:zt.type,mesh,pop:0,jobs:0};if(zt.type==='res')b.pop=Math.round(8+h*.9);if(zt.type==='com')b.jobs=Math.round(8+h*.65);if(zt.type==='ind')b.jobs=Math.round(10+w*d/95);buildings.push(b);state.population+=b.pop;state.jobs+=b.jobs;return true}
export function bulldoze(x,z,r=28){let best=null,bd=Infinity;for(const b of buildings){const d=Math.hypot(b.mesh.position.x-x,b.mesh.position.z-z);if(d<bd){bd=d;best=b}}if(best&&bd<r){scene.remove(best.mesh);state.population-=best.pop;state.jobs-=best.jobs;buildings.splice(buildings.indexOf(best),1);return}for(const zt of zones){if(Math.hypot(zt.x-x,zt.z-z)<r){scene.remove(zt.mesh);zoneSet.delete(key(zt.x,zt.z));zones.splice(zones.indexOf(zt),1);return}}}
function spawnCar(){if(!roadCurves.length||cars.length>90)return;const curve=roadCurves[(Math.random()*roadCurves.length)|0],mesh=new THREE.Mesh(new THREE.BoxGeometry(4.2,2.2,8.5),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(Math.random(),.55,.48),roughness:.45,metalness:.15}));mesh.castShadow=true;scene.add(mesh);cars.push({mesh,curve,t:Math.random(),speed:.018+Math.random()*.026,dir:Math.random()<.5?1:-1})}
for(let i=0;i<20;i++)spawnCar();let growT=0,carT=0;
export function simulate(dt){if(state.paused)return;const sdt=dt*state.speed;state.hour=(state.hour+sdt*.07)%24;growT+=sdt;carT+=sdt;state.money+=sdt*(state.population*.035+state.jobs*.012-roads.length*6.5);if(growT>.7){growT=0;for(const z of zones)if(!z.built&&Math.random()<.07*state.speed){grow(z);break}}if(carT>1.4){carT=0;spawnCar()}for(const c of cars){c.t+=c.speed*sdt*c.dir;if(c.t>1)c.t=0;if(c.t<0)c.t=1;const p=c.curve.getPointAt(c.t),p2=c.curve.getPointAt(THREE.MathUtils.clamp(c.t+.002*c.dir,.001,.999));c.mesh.position.set(p.x,terrainHeight(p.x,p.z)+2.1,p.z);c.mesh.rotation.y=Math.atan2(p2.x-p.x,p2.z-p.z)}}
