import {THREE,cam,HALF,terrainHeight,screenToTerrain,scene} from './engine.js';
import {state,paintZone,bulldoze,makeRoad,previewRoad} from './city.js';
const canvas=document.getElementById('hudCanvas'),ctx=canvas.getContext('2d');export const ui={tool:'inspect',stage:0,points:[],notice:'Build the city. Every world unit = 1 metre.',hit:[],dragZone:false};let preview=null;
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function button(x,y,w,h,label,tool,accent){const a=ui.tool===tool;rr(x,y,w,h,12,a?(accent||'rgba(64,157,215,.92)'):'rgba(8,20,28,.88)','rgba(255,255,255,.13)');ctx.fillStyle='#fff';ctx.font='600 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x+w/2,y+h/2);ui.hit.push({x,y,w,h,tool})}
export function drawHUD(){const W=innerWidth,H=innerHeight;ctx.clearRect(0,0,W,H);ui.hit=[];const topW=Math.min(760,W-28);rr(14,14,topW,64,16,'rgba(5,16,23,.88)','rgba(255,255,255,.10)');ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle='#f4fbff';ctx.font='700 18px system-ui';ctx.fillText('CITYFORGE',30,40);ctx.fillStyle='rgba(226,241,248,.72)';ctx.font='500 11px system-ui';ctx.fillText('ENGINE PROTOTYPE · 16 km × 16 km · 1 unit = 1 m',30,58);const stats=[['$'+Math.round(state.money).toLocaleString(),'Budget'],[state.population.toLocaleString(),'Population'],[state.jobs.toLocaleString(),'Jobs'],[(state.paused?'PAUSED':state.speed+'×'),'Speed'],[`${String(Math.floor(state.hour)).padStart(2,'0')}:${String(Math.floor((state.hour%1)*60)).padStart(2,'0')}`,'Time']];let sx=Math.max(210,topW-500)+14;for(const [v,l] of stats){ctx.fillStyle='#fff';ctx.font='700 13px system-ui';ctx.fillText(v,sx,39);ctx.fillStyle='rgba(220,235,243,.58)';ctx.font='500 9px system-ui';ctx.fillText(l,sx,56);sx+=92}const barW=Math.min(650,W-24),barX=(W-barW)/2,barY=H-78;rr(barX,barY,barW,62,18,'rgba(5,16,23,.92)','rgba(255,255,255,.12)');const gap=7,bw=(barW-28-gap*5)/6;let x=barX+14;button(x,barY+11,bw,40,'Inspect','inspect');x+=bw+gap;button(x,barY+11,bw,40,'Roads','road','#1f92c9');x+=bw+gap;button(x,barY+11,bw,40,'Residential','res','#2e9e57');x+=bw+gap;button(x,barY+11,bw,40,'Commercial','com','#327fd3');x+=bw+gap;button(x,barY+11,bw,40,'Industry','ind','#c68b32');x+=bw+gap;button(x,barY+11,bw,40,'Bulldoze','bulldoze','#b64b48');rr(14,H-142,Math.min(430,W-28),50,13,'rgba(5,16,23,.78)','rgba(255,255,255,.08)');ctx.fillStyle='#fff';ctx.font='600 12px system-ui';ctx.textAlign='left';const msg=ui.tool==='road'?(ui.stage===0?'Road: click START':ui.stage===1?'Road: click CONTROL point':'Road: click END to build spline'):['res','com','ind'].includes(ui.tool)?'Hold / drag to paint zoning. Growth requires road access.':ui.tool==='bulldoze'?'Click a zoned lot or building to remove it.':'Drag to pan · Right drag/Q/E rotate · Wheel/pinch zoom';ctx.fillText(msg,28,H-113);ctx.fillStyle='rgba(215,233,242,.62)';ctx.font='500 10px system-ui';ctx.fillText(ui.notice,28,H-96);const cx=W-168,cy=18;for(let i=0;i<4;i++){const labels=['II','1×','2×','4×'];rr(cx+i*37,cy,32,28,8,'rgba(7,22,31,.86)','rgba(255,255,255,.12)');ctx.fillStyle='#fff';ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(labels[i],cx+i*37+16,cy+14);ui.hit.push({x:cx+i*37,y:cy,w:32,h:28,control:i})}}
function clearPreview(){if(preview){scene.remove(preview);preview.geometry.dispose();preview=null}}
function updatePreview(p){clearPreview();if(ui.tool!=='road'||!p||ui.stage===0)return;let pts;if(ui.stage===1){const a=ui.points[0],mid=a.clone().lerp(p,.5);pts=[a,mid,p]}else pts=[ui.points[0],ui.points[1],p];preview=previewRoad(pts);scene.add(preview)}
function worldClick(p){if(!p)return;if(ui.tool==='road'){if(ui.stage===0){ui.points=[p];ui.stage=1;ui.notice='Start locked.'}else if(ui.stage===1){ui.points.push(p);ui.stage=2;ui.notice='Control locked. Choose end.'}else{const pts=[...ui.points,p],res=makeRoad(pts);ui.notice=res?`Built ${Math.round(res.len)} m road · $${res.cost.toLocaleString()}`:'Not enough budget.';ui.points=[];ui.stage=0;clearPreview()}}else if(['res','com','ind'].includes(ui.tool)){for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)paintZone(ui.tool,p.x+dx*32,p.z+dz*32)}else if(ui.tool==='bulldoze')bulldoze(p.x,p.z)}
function hit(x,y){return ui.hit.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h)}
let down=false,right=false,lx=0,ly=0,moved=0,pinch=0;const pts=new Map();canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===2){const a=[...pts.values()];pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);down=false;return}const h=hit(e.clientX,e.clientY);if(h){if(h.tool){ui.tool=h.tool;ui.stage=0;ui.points=[];clearPreview()}if(h.control!==undefined){if(h.control===0)state.paused=!state.paused;else{state.paused=false;state.speed=[0,1,2,4][h.control]}}return}down=true;right=e.button===2;lx=e.clientX;ly=e.clientY;moved=0;if(['res','com','ind'].includes(ui.tool)){ui.dragZone=true;worldClick(screenToTerrain(e.clientX,e.clientY))}});
canvas.addEventListener('pointermove',e=>{if(pts.has(e.pointerId))pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===2){const a=[...pts.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch>0){cam.distance*=pinch/Math.max(20,d);cam.distance=THREE.MathUtils.clamp(cam.distance,110,6500)}pinch=d;return}const p=screenToTerrain(e.clientX,e.clientY);updatePreview(p);if(down){const dx=e.clientX-lx,dy=e.clientY-ly;moved+=Math.abs(dx)+Math.abs(dy);if(ui.dragZone&&p)worldClick(p);else if(right||e.shiftKey){cam.yaw-=dx*.006;cam.pitch=THREE.MathUtils.clamp(cam.pitch-dy*.003,THREE.MathUtils.degToRad(24),THREE.MathUtils.degToRad(72))}else if(ui.tool==='inspect'||ui.tool==='bulldoze'){const sc=cam.distance*.0012,f=new THREE.Vector3(-Math.sin(cam.yaw),0,-Math.cos(cam.yaw)),r=new THREE.Vector3(Math.cos(cam.yaw),0,-Math.sin(cam.yaw));cam.target.addScaledVector(r,-dx*sc);cam.target.addScaledVector(f,dy*sc)}lx=e.clientX;ly=e.clientY}});
canvas.addEventListener('pointerup',e=>{pts.delete(e.pointerId);if(pts.size<2)pinch=0;if(down&&moved<8&&!ui.dragZone)worldClick(screenToTerrain(e.clientX,e.clientY));down=false;right=false;ui.dragZone=false});canvas.addEventListener('wheel',e=>{e.preventDefault();cam.distance*=Math.exp(e.deltaY*.001);cam.distance=THREE.MathUtils.clamp(cam.distance,110,6500)},{passive:false});
const keys=new Set();addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));export function updateInput(dt){const pace=Math.max(120,cam.distance*.6)*dt,f=new THREE.Vector3(-Math.sin(cam.yaw),0,-Math.cos(cam.yaw)),r=new THREE.Vector3(Math.cos(cam.yaw),0,-Math.sin(cam.yaw));if(keys.has('w'))cam.target.addScaledVector(f,pace);if(keys.has('s'))cam.target.addScaledVector(f,-pace);if(keys.has('a'))cam.target.addScaledVector(r,-pace);if(keys.has('d'))cam.target.addScaledVector(r,pace);if(keys.has('q'))cam.yaw+=dt;if(keys.has('e'))cam.yaw-=dt;cam.target.x=THREE.MathUtils.clamp(cam.target.x,-HALF+300,HALF-300);cam.target.z=THREE.MathUtils.clamp(cam.target.z,-HALF+300,HALF-300);cam.target.y=terrainHeight(cam.target.x,cam.target.z)+15}
export function resizeHUD(){canvas.width=Math.floor(innerWidth*devicePixelRatio);canvas.height=Math.floor(innerHeight*devicePixelRatio);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resizeHUD);resizeHUD();
